export type Recipe = {
  id: string;
  title: string;
  description: string;
  image: string;
  category: string;
  time: string;
  difficulty: "Easy" | "Medium" | "Hard";
  rating: number;
  author: string;
  authorAvatar: string;
  ingredients: string[];
  steps: string[];
  tags: string[];
  servings: number;
  calories: number;
};

const img = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1200&q=70`;

export const recipes: Recipe[] = [
  {
    id: "1",
    title: "Creamy Tuscan Chicken",
    description:
      "Pan-seared chicken swimming in a garlicky sun-dried tomato cream sauce.",
    image: img("1546069901-ba9599a7e63c"),
    category: "Italian",
    time: "35 min",
    difficulty: "Medium",
    rating: 4.8,
    author: "Aria Bennett",
    authorAvatar: "https://i.pravatar.cc/100?img=32",
    ingredients: [
      "4 chicken breasts",
      "1 cup heavy cream",
      "1/2 cup sun-dried tomatoes",
      "3 cloves garlic",
      "Fresh basil",
      "Parmesan cheese",
    ],
    steps: [
      "Season and sear chicken until golden.",
      "Sauté garlic and sun-dried tomatoes.",
      "Add cream and simmer until thickened.",
      "Return chicken, top with basil and parmesan.",
    ],
    tags: ["dinner", "creamy", "chicken"],
    servings: 4,
    calories: 520,
  },
  {
    id: "2",
    title: "Matcha Berry Pancakes",
    description: "Fluffy stack of matcha pancakes with fresh summer berries.",
    image: img("1528207776546-365bb710ee93"),
    category: "Breakfast",
    time: "20 min",
    difficulty: "Easy",
    rating: 4.6,
    author: "Kaito Mori",
    authorAvatar: "https://i.pravatar.cc/100?img=12",
    ingredients: [
      "1 cup flour",
      "2 tsp matcha powder",
      "1 cup milk",
      "1 egg",
      "Mixed berries",
      "Maple syrup",
    ],
    steps: [
      "Whisk dry and wet ingredients separately.",
      "Combine and rest for 5 minutes.",
      "Cook on medium heat until bubbles form.",
      "Stack, top with berries and syrup.",
    ],
    tags: ["breakfast", "vegetarian"],
    servings: 2,
    calories: 380,
  },
  {
    id: "3",
    title: "Smoky Chipotle Tacos",
    description: "Slow-braised beef tacos with charred pineapple salsa.",
    image: img("1565299585323-38d6b0865b47"),
    category: "Mexican",
    time: "1 hr",
    difficulty: "Medium",
    rating: 4.9,
    author: "Sofia Reyes",
    authorAvatar: "https://i.pravatar.cc/100?img=45",
    ingredients: [
      "1 lb beef chuck",
      "2 chipotle peppers",
      "Pineapple",
      "Red onion",
      "Corn tortillas",
      "Cilantro",
    ],
    steps: [
      "Braise beef with chipotle for 45 min.",
      "Char pineapple on a hot pan.",
      "Chop and mix the salsa.",
      "Warm tortillas and assemble.",
    ],
    tags: ["tacos", "spicy"],
    servings: 4,
    calories: 460,
  },
  {
    id: "4",
    title: "Lemon Herb Salmon",
    description: "Oven-baked salmon with a bright lemon herb crust.",
    image: img("1467003909585-2f8a72700288"),
    category: "Seafood",
    time: "25 min",
    difficulty: "Easy",
    rating: 4.7,
    author: "Noor Hassan",
    authorAvatar: "https://i.pravatar.cc/100?img=5",
    ingredients: ["Salmon fillet", "Lemon", "Dill", "Garlic", "Olive oil"],
    steps: [
      "Preheat oven to 200°C.",
      "Coat salmon in herbs and lemon.",
      "Bake for 15 minutes.",
      "Rest and serve with greens.",
    ],
    tags: ["healthy", "seafood"],
    servings: 2,
    calories: 340,
  },
  {
    id: "5",
    title: "Dark Chocolate Lava Cake",
    description: "Molten centered chocolate cakes served warm.",
    image: img("1606313564200-e75d5e30476c"),
    category: "Dessert",
    time: "30 min",
    difficulty: "Medium",
    rating: 4.9,
    author: "Elena Rossi",
    authorAvatar: "https://i.pravatar.cc/100?img=47",
    ingredients: ["Dark chocolate", "Butter", "Eggs", "Sugar", "Flour"],
    steps: [
      "Melt chocolate and butter together.",
      "Whisk eggs and sugar until pale.",
      "Fold and pour into ramekins.",
      "Bake for 10-12 minutes.",
    ],
    tags: ["dessert", "chocolate"],
    servings: 4,
    calories: 480,
  },
  {
    id: "6",
    title: "Rainbow Buddha Bowl",
    description: "Colorful grain bowl with tahini dressing and roasted veg.",
    image: img("1512621776951-a57141f2eefd"),
    category: "Vegetarian",
    time: "40 min",
    difficulty: "Easy",
    rating: 4.5,
    author: "Maya Okonkwo",
    authorAvatar: "https://i.pravatar.cc/100?img=20",
    ingredients: ["Quinoa", "Chickpeas", "Sweet potato", "Kale", "Tahini"],
    steps: [
      "Roast sweet potato and chickpeas.",
      "Cook quinoa.",
      "Massage kale with lemon.",
      "Assemble and drizzle tahini.",
    ],
    tags: ["healthy", "vegan"],
    servings: 2,
    calories: 520,
  },
  {
    id: "7",
    title: "Classic Margherita Pizza",
    description: "Wood-fired style pizza with fresh mozzarella and basil.",
    image: img("1513104890138-7c749659a591"),
    category: "Italian",
    time: "50 min",
    difficulty: "Medium",
    rating: 4.8,
    author: "Marco Bianchi",
    authorAvatar: "https://i.pravatar.cc/100?img=15",
    ingredients: ["Pizza dough", "San Marzano tomatoes", "Mozzarella", "Basil"],
    steps: [
      "Stretch the dough thin.",
      "Top with tomato and cheese.",
      "Bake at highest oven temp.",
      "Finish with basil and olive oil.",
    ],
    tags: ["pizza", "vegetarian"],
    servings: 2,
    calories: 620,
  },
  {
    id: "8",
    title: "Thai Green Curry",
    description: "Aromatic coconut green curry with chicken and Thai basil.",
    image: img("1455619452474-d2be8b1e70cd"),
    category: "Thai",
    time: "45 min",
    difficulty: "Medium",
    rating: 4.7,
    author: "Ploy Suwan",
    authorAvatar: "https://i.pravatar.cc/100?img=25",
    ingredients: ["Green curry paste", "Coconut milk", "Chicken", "Thai basil"],
    steps: [
      "Fry curry paste in coconut cream.",
      "Add chicken and simmer.",
      "Pour in coconut milk.",
      "Finish with basil and lime.",
    ],
    tags: ["spicy", "asian"],
    servings: 4,
    calories: 540,
  },
];

export const categories = [
  { name: "Breakfast", emoji: "🥞", count: 42 },
  { name: "Italian", emoji: "🍝", count: 68 },
  { name: "Mexican", emoji: "🌮", count: 35 },
  { name: "Seafood", emoji: "🐟", count: 27 },
  { name: "Dessert", emoji: "🍰", count: 54 },
  { name: "Vegetarian", emoji: "🥗", count: 61 },
  { name: "Thai", emoji: "🍜", count: 22 },
  { name: "BBQ & Grill", emoji: "🔥", count: 18 },
  { name: "Baking", emoji: "🥖", count: 39 },
  { name: "Drinks", emoji: "🍹", count: 24 },
  { name: "Salads", emoji: "🥙", count: 31 },
  { name: "Soups", emoji: "🥣", count: 19 },
];
